[2023-12-04T15:47:41.095+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_v03.insert_post_ manual__2023-12-04T15:47:38.656930+00:00 [queued]>
[2023-12-04T15:47:41.109+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_v03.insert_post_ manual__2023-12-04T15:47:38.656930+00:00 [queued]>
[2023-12-04T15:47:41.110+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-04T15:47:41.135+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_post_> on 2023-12-04 15:47:38.656930+00:00
[2023-12-04T15:47:41.141+0000] {standard_task_runner.py:57} INFO - Started process 74313 to run task
[2023-12-04T15:47:41.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v03', 'insert_post_', 'manual__2023-12-04T15:47:38.656930+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp3n5clc2c']
[2023-12-04T15:47:41.149+0000] {standard_task_runner.py:85} INFO - Job 275: Subtask insert_post_
[2023-12-04T15:47:41.216+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_v03.insert_post_ manual__2023-12-04T15:47:38.656930+00:00 [running]> on host a859eb4bf49d
[2023-12-04T15:47:41.279+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'insert_post_', field 'sql'. Template: "\n            insert into dag_runs (dt, dag_id) values ('{{dt}}', '{{dag.dag_id}}')\n\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2023-12-04T15:47:41.285+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2023-12-04T15:47:41.301+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v03, task_id=insert_post_, execution_date=20231204T154738, start_date=20231204T154741, end_date=20231204T154741
[2023-12-04T15:47:41.315+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 275 for task insert_post_ ('dt' is undefined; 74313)
[2023-12-04T15:47:41.359+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T15:47:41.384+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
