[2023-12-04T14:22:21.165+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_v01.create_post_ scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-12-04T14:22:21.182+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_v01.create_post_ scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-12-04T14:22:21.183+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-04T14:22:21.210+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_post_> on 2023-11-09 00:00:00+00:00
[2023-12-04T14:22:21.217+0000] {standard_task_runner.py:57} INFO - Started process 68008 to run task
[2023-12-04T14:22:21.234+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v01', 'create_post_', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp7f7fi5f8']
[2023-12-04T14:22:21.238+0000] {standard_task_runner.py:85} INFO - Job 229: Subtask create_post_
[2023-12-04T14:22:21.327+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_v01.create_post_ scheduled__2023-11-09T00:00:00+00:00 [running]> on host a859eb4bf49d
[2023-12-04T14:22:21.456+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='debora' AIRFLOW_CTX_DAG_ID='dag_with_postgres_v01' AIRFLOW_CTX_TASK_ID='create_post_' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-12-04T14:22:21.458+0000] {sql.py:274} INFO - Executing: 
        
            create table if not exists dag_runs(
            dt date, 
            dag_id charater varying
            primary key (dt, dag_id)
            )
            
        
[2023-12-04T14:22:21.473+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-04T14:22:21.487+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-04T14:22:29.495+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2023-12-04T14:22:29.511+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v01, task_id=create_post_, execution_date=20231109T000000, start_date=20231204T142221, end_date=20231204T142229
[2023-12-04T14:22:29.533+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 229 for task create_post_ (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 68008)
[2023-12-04T14:22:29.551+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T14:22:29.582+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
