[2023-12-05T09:40:32.755+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python.get_sklearn scheduled__2023-12-04T00:00:00+00:00 [queued]>
[2023-12-05T09:40:32.771+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python.get_sklearn scheduled__2023-12-04T00:00:00+00:00 [queued]>
[2023-12-05T09:40:32.772+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-05T09:40:32.808+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-12-04 00:00:00+00:00
[2023-12-05T09:40:32.813+0000] {standard_task_runner.py:57} INFO - Started process 47145 to run task
[2023-12-05T09:40:32.816+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python', 'get_sklearn', 'scheduled__2023-12-04T00:00:00+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python.py', '--cfg-path', '/tmp/tmpf17qpxak']
[2023-12-05T09:40:32.820+0000] {standard_task_runner.py:85} INFO - Job 305: Subtask get_sklearn
[2023-12-05T09:40:32.877+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_python.get_sklearn scheduled__2023-12-04T00:00:00+00:00 [running]> on host a859eb4bf49d
[2023-12-05T09:40:33.033+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='debora' AIRFLOW_CTX_DAG_ID='dag_with_python' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-04T00:00:00+00:00'
[2023-12-05T09:40:33.066+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-12-05T09:40:33.110+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python, task_id=get_sklearn, execution_date=20231204T000000, start_date=20231205T094032, end_date=20231205T094033
[2023-12-05T09:40:33.143+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 305 for task get_sklearn (No module named 'sklearn'; 47145)
[2023-12-05T09:40:33.152+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-05T09:40:33.174+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
