[2023-12-05T13:44:45.668+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_hook_v1.upload_to_s3 scheduled__2023-12-04T03:00:00+00:00 [queued]>
[2023-12-05T13:44:45.684+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_hook_v1.upload_to_s3 scheduled__2023-12-04T03:00:00+00:00 [queued]>
[2023-12-05T13:44:45.685+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-05T13:44:45.712+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2023-12-04 03:00:00+00:00
[2023-12-05T13:44:45.719+0000] {standard_task_runner.py:57} INFO - Started process 13795 to run task
[2023-12-05T13:44:45.724+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_hook_v1', 'upload_to_s3', 'scheduled__2023-12-04T03:00:00+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_with_hook.py', '--cfg-path', '/tmp/tmpdamomngz']
[2023-12-05T13:44:45.729+0000] {standard_task_runner.py:85} INFO - Job 353: Subtask upload_to_s3
[2023-12-05T13:44:45.807+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_hook_v1.upload_to_s3 scheduled__2023-12-04T03:00:00+00:00 [running]> on host 0c998a8be895
[2023-12-05T13:44:45.950+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='debora' AIRFLOW_CTX_DAG_ID='dag_with_hook_v1' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-04T03:00:00+00:00'
[2023-12-05T13:44:45.967+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-05T13:44:45.979+0000] {logging_mixin.py:154} INFO - connected to postgres
[2023-12-05T13:44:45.987+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_with_hook.py", line 22, in postgres_to_s3
    cursor.execute("select * from orders where date <=20220501")
psycopg2.errors.UndefinedFunction: operator does not exist: date <= integer
LINE 1: select * from orders where date <=20220501
                                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2023-12-05T13:44:46.001+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_hook_v1, task_id=upload_to_s3, execution_date=20231204T030000, start_date=20231205T134445, end_date=20231205T134446
[2023-12-05T13:44:46.019+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 353 for task upload_to_s3 (operator does not exist: date <= integer
LINE 1: select * from orders where date <=20220501
                                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 13795)
[2023-12-05T13:44:46.060+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-05T13:44:46.093+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
